In [1]:
import tensorflow as tf
import numpy as np


%load_ext autoreload
%autoreload 2
from preprocessing import tokenize, preprocess, load_data
from transformer import EncoderBlock, TransformerBlock, PositionalEncoding
# from Model_2 import WordCaptionModel
from model import NewsCaptionModel

# Load the data

In [2]:
dataset = load_data("data/subset")

In [3]:
inputs = dataset["inputs"]
labels = dataset["labels"]

In [46]:
labels.shape

(5000, 20)

In [4]:
vocab_size = len(dataset["word2idx"].items())
vocab_size

3099

In [6]:
# summarized.numpy().reshape(10, -1)[0]÷

NameError: name 'summarized' is not defined

In [84]:
def perplexity(y_true, y_pred):
    tf.print(y_pred)
    return tf.exp(tf.reduce_mean(tf.keras.metrics.sparse_categorical_crossentropy(y_true, y_pred)))

# Create the model

In [85]:
encoder = EncoderBlock(124, vocab_size=vocab_size)
decoder = TransformerBlock(124, vocab_size)
news_model = NewsCaptionModel(encoder, decoder)

In [86]:
news_model.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics = perplexity
)

In [87]:
news_model.fit(
    [inputs, labels],
    labels,
    epochs=10, 
    batch_size=25,
    validation_data=([inputs, labels], labels)
)

Epoch 1/10


2022-12-11 16:29:57.068823: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


[[[0 0 0 ... 0 0.424331933 0]
  [2.25216866 0 0 ... 0 0 0]
  [0 0 0 ... 0 0.393820018 0]
  ...
  [2.22370028 0 0 ... 0 0.342719615 0]
  [2.21862173 0 0 ... 0 0.394672215 0]
  [2.23714161 0 0 ... 0 0 0]]

 [[2.26851201 0 0 ... 0 0 0]
  [2.25593662 0 0 ... 0 0.37724188 0]
  [2.27327 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0.349405825 0]
  [0 0 0 ... 0 0.391031295 0]
  [2.24392104 0 0 ... 0 0 0]]

 [[2.28934479 0 0 ... 0 0 0]
  [2.27472544 0 0 ... 0 0.418242067 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0.401660681 0]
  [2.27468657 0 0 ... 0 0.4165124 0]]

 ...

 [[2.19964623 0 0 ... 0 0 0]
  [2.14635968 0 0 ... 0 0 0]
  [2.18427372 0 0 ... 0 0.42364347 0]
  ...
  [2.18427372 0 0 ... 0 0.42364347 0]
  [2.18427372 0 0 ... 0 0 0]
  [2.15949225 0 0 ... 0 0.413223 0]]

 [[2.26962376 0 0 ... 0 0.432590723 0]
  [2.25932407 0 0 ... 0 0.427235872 0]
  [0 0 0 ... 0 0.421454668 0]
  ...
  [2.28972054 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[2.24491978 0 0 ... 0 0

KeyboardInterrupt: 

In [70]:
# model([inputs, labels])
news_model.fit(
    [inputs, labels],
    labels,
    epochs=10, 
    batch_size=25,
    validation_data=([inputs, labels], labels)
)
# model.build(input_shape=(None, 124))

Epoch 1/10


2022-12-11 15:54:43.685670: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


200/200 [==============================] - ETA: 0s - loss: 5.7516 - perplexity: 339.7911

2022-12-11 15:55:12.023582: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


200/200 [==============================] - 38s 169ms/step - loss: 5.7516 - perplexity: 339.7911 - val_loss: 5.6809 - val_perplexity: 309.4752
Epoch 2/10
200/200 [==============================] - 33s 163ms/step - loss: 5.6913 - perplexity: 314.9542 - val_loss: 5.6840 - val_perplexity: 310.9508
Epoch 3/10
200/200 [==============================] - 32s 158ms/step - loss: 5.6885 - perplexity: 317.6306 - val_loss: 5.6840 - val_perplexity: 310.9508
Epoch 4/10
200/200 [==============================] - 31s 153ms/step - loss: 5.6914 - perplexity: 313.3600 - val_loss: 5.6840 - val_perplexity: 310.9510
Epoch 5/10
200/200 [==============================] - 29s 146ms/step - loss: 5.6608 - perplexity: 302.4050 - val_loss: 5.6840 - val_perplexity: 310.9517
Epoch 6/10
200/200 [==============================] - 29s 143ms/step - loss: 5.6841 - perplexity: 311.8976 - val_loss: 5.6840 - val_perplexity: 310.9508
Epoch 7/10
200/200 [==============================] - 29s 145ms/step - loss: 5.6941 - perplex

In [107]:
news_model.history.history

{}

In [75]:
samples = (inputs[:10], labels[:10])
outputs = news_model.predict(samples)

1/1 [==============================] - 0s 337ms/step


In [41]:
[dataset["idx2word"][i] for i in labels[]]

['<start>',
 'craig',
 '<unk>',
 '27',
 'had',
 'drunk',
 'at',
 'least',
 'three',
 '<unk>',
 'before',
 'driving',
 'car',
 'wa',
 'using',
 'phone',
 'when',
 'he',
 '<unk>',
 '<end>']

In [101]:
for i in range(10):
    sentence = labels[i]
    print(" ".join([dataset["idx2word"][i] for i in sentence]))
#     generate_sentense(sentence)

<start> bishop john <unk> of north <unk> is taking time off after being diagnosed he <unk> the infection through <end>
<start> criminal complaint cop used his role to help cocaine <unk> <unk> <unk> an internal affair <unk> allegedly helped <end>
<start> craig <unk> 27 had drunk at least three <unk> before driving car wa using phone when he <unk> <end>
<start> <unk> do <unk> say europe must be ready to accept sanction will hurt both side <unk> russia business <end>
<start> <unk> top of league one after 20 win at <unk> <unk> <unk> city <unk> and <unk> all drop <end>
<start> prime minister and his family are enjoying an <unk> break in <unk> <unk> the same <unk> <unk> <unk> <end>
<start> <unk> star call for black and <unk> community to get tested former <unk> player dedicated life to raising <end>
<start> london <unk> service had been <unk> into <unk> station in <unk> passenger chris <unk> 46 wa recording on <end>
<start> tony <unk> belief <unk> <unk> should look up to <unk> <unk> <unk> <u

In [76]:
generate_sentense(outputs)

in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in
in in in in in in in in in in in in in in in in in in in in


In [67]:
news_model.summary()

Model: "news_caption_model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 encoder_block_5 (EncoderBlo  multiple                 569284    
 ck)                                                             
                                                                 
 transformer_block_5 (Transf  multiple                 630416    
 ormerBlock)                                                     
                                                                 
Total params: 1,199,700
Trainable params: 1,199,700
Non-trainable params: 0
_________________________________________________________________


In [43]:
def generate_sentense(outputs):
    batch_size = outputs.shape[0]
    for i in range(batch_size):
        sentence = outputs[i]
        sentence = np.argmax(sentence, axis=-1)
        print(" ".join([dataset["idx2word"][i] for i in sentence]))
    